// Array of quotes for "Had a bad day"
const badDayQuotes = [
  "Indeed, with hardship [will be] ease. – Quran 94:6",
  "And He is with you wherever you are. – Quran 57:4",
  "Do not lose hope, nor be sad. – Quran 3:139",
  "Your Lord has not taken leave of you, nor has He become displeased. – Quran 93:3",
  "So verily, with the hardship, there is relief. – Quran 94:5",
  "And whoever fears Allah – He will make for him a way out. – Quran 65:2",
  "Indeed, Allah is with the patient. – Quran 2:153",
  "And He found you lost and guided [you]. – Quran 93:7",
  "Say, 'O My servants who have believed, fear your Lord. For those who do good in this world is good, and the earth of Allah is spacious.' – Quran 39:10",
  "Indeed, the promise of Allah is truth. – Quran 10:55",
  "Every day may not be good, but there is something good in every day. – Alice Morse Earle",
  "The darkest nights produce the brightest stars. – John Green",
  "Don't watch the clock; do what it does. Keep going. – Sam Levenson",
  "It’s not whether you get knocked down, it’s whether you get up. – Vince Lombardi",
  "In the middle of every difficulty lies opportunity. – Albert Einstein",
  "When you’re at the end of your rope, tie a knot and hold on. – Theodore Roosevelt",
  "You are never too old to set another goal or to dream a new dream. – C.S. Lewis",
  "The only way out is through. – Robert Frost",
  "Believe you can and you’re halfway there. – Theodore Roosevelt",
  "Turn your wounds into wisdom. – Oprah Winfrey",
  "And He knows what is within the breasts. – Quran 67:13",
  "Indeed, Allah does not burden a soul beyond that it can bear. – Quran 2:286",
  "And whoever relies upon Allah – then He is sufficient for him. – Quran 65:3",
  "Indeed, Allah is the best of planners. – Quran 8:30",
  "And We will surely give them a taste of the lesser punishment. – Quran 32:21",
  "And do not despair of the mercy of Allah. – Quran 39:53",
  "Indeed, Allah does not change the condition of a people until they change what is in themselves. – Quran 13:11",
  "And do not kill yourselves [or one another]. – Quran 4:29",
  "And We have certainly made the Quran easy to remember. So is there any who will remember? – Quran 54:17",
  "And We have sent you, [O Muhammad], as a mercy to the worlds. – Quran 21:107",
  "The best way to predict the future is to create it. – Peter Drucker",
  "Keep your face always toward the sunshine—and shadows will fall behind you. – Walt Whitman",
  "You are stronger than you think. – Unknown",
  "Do not wait to strike till the iron is hot, but make it hot by striking. – William Butler Yeats",
  "What lies behind us and what lies before us are tiny matters compared to what lies within us. – Ralph Waldo Emerson",
  "You are never given a wish without also being given the power to make it come true. – Richard Bach",
  "Courage doesn’t always roar. Sometimes courage is the quiet voice at the end of the day saying, 'I will try again tomorrow.' – Mary Anne Radmacher",
  "The only limit to our realization of tomorrow will be our doubts of today. – Franklin D. Roosevelt",
  "You can’t go back and change the beginning, but you can start where you are and change the ending. – C.S. Lewis",
  "This too shall pass. – Persian Proverb",
  "And whoever is guided is only guided for the benefit of his soul. – Quran 17:15",
  "So be patient. Indeed, the promise of Allah is truth. – Quran 30:60",
  "And your Lord says, 'Call upon Me; I will respond to you.' – Quran 40:60",
  "And if you should count the favors of Allah, you could not enumerate them. – Quran 14:34",
  "Indeed, He is the Most Forgiving, the Most Merciful. – Quran 39:53",
  "And We will surely test you with something of fear and hunger. – Quran 2:155",
  "And We have not sent you, [O Muhammad], except as a mercy to the worlds. – Quran 21:107",
  "Indeed, the righteous will be in pleasure. – Quran 83:22",
  "Say, 'It is He who has created you and made for you hearing and vision and hearts; little are you grateful.' – Quran 67:23",
  "So be grateful to Allah if it is Him that you worship. – Quran 16:14",
  "The future belongs to those who believe in the beauty of their dreams. – Eleanor Roosevelt",
  "Success is not final, failure is not fatal: It is the courage to continue that counts. – Winston Churchill",
  "Happiness is not something ready made. It comes from your own actions. – Dalai Lama",
  "You are enough just as you are. – Brené Brown",
  "Act as if what you do makes a difference. It does. – William James",
  "What we think, we become. – Buddha",
  "The only impossible journey is the one you never begin. – Tony Robbins",
  "Everything you’ve ever wanted is on the other side of fear. – George Addair",
  "Sometimes you will never know the value of a moment until it becomes a memory. – Dr. Seuss",
  "You are braver than you believe, stronger than you seem, and smarter than you think. – A.A. Milne",
  "Indeed, your allies are none but Allah and His Messenger and those who have believed. – Quran 5:55",
  "And We have made the night and the day as two signs. – Quran 17:12",
  "Indeed, We created man and We know what his soul whispers to him. – Quran 50:16",
  "And your Lord will give you, and you will be satisfied. – Quran 93:5",
  "And We will show them Our signs in the horizons and within themselves. – Quran 41:53",
  "And do not despair over their [disbelievers'] speech. – Quran 36:76",
  "Indeed, Allah is the best of planners. – Quran 8:30",
  "And if you ask them, 'Who created the heavens and the earth?' They would surely say, 'Allah.' – Quran 31:25",
  "Indeed, those who have believed and done righteous deeds – the Most Merciful will appoint for them affection. – Quran 19:96",
  "And We will certainly give them a taste of the lesser punishment. – Quran 32:21",
  "Dream big and dare to fail. – Norman Vaughan",
  "The pain you feel today is the strength you feel tomorrow. – Unknown",
  "Believe in yourself and all that you are. – Christian D. Larson",
  "The best way out is always through. – Robert Frost",
  "Keep going. Each step may get harder, but don’t stop. The view is beautiful at the top. – Unknown",
  "Don’t be pushed around by the fears in your mind. Be led by the dreams in your heart. – Roy T. Bennett",
  "You don’t have to be great to start, but you have to start to be great. – Zig Ziglar",
  "Every moment is a fresh beginning. – T.S. Eliot",
  "Life is 10% what happens to us and 90% how we react to it. – Charles R. Swindoll",
  "Life isn’t about finding yourself. Life is about creating yourself. – George Bernard Shaw",
  "And We will surely test you with something of fear and hunger. – Quran 2:155",
  "And do not lose hope in the mercy of Allah. – Quran 39:53",
  "Say, 'It is He who created you from one soul and made its mate.' – Quran 7:189",
  "And if you are grateful, I will surely increase your favor. – Quran 14:7",
  "Indeed, Allah will not change the condition of a people until they change what is in themselves. – Quran 13:11",
  "And We are closer to him than [his] jugular vein. – Quran 50:16",
  "And We have created you in pairs. – Quran 78:8",
  "And whoever does an atom's weight of good will see it. – Quran 99:7",
  "Indeed, the righteous will be in pleasure. – Quran 83:22",
  "And He found you lost and guided [you]. – Quran 93:7",
  "It does not matter how slowly you go as long as you do not stop. – Confucius",
  "Your present circumstances don’t determine where you can go; they merely determine where you start. – Nido Qubein",
  "It always seems impossible until it is done. – Nelson Mandela",
  "And do not kill yourselves [or one another]. – Quran 4:29",
  "And whoever fears Allah – He will make for him a way out. – Quran 65:2",
  "The only limit to our realization of tomorrow will be our doubts of today. – Franklin D. Roosevelt",
  "And if you should count the favors of Allah, you could not enumerate them. – Quran 14:34",
  "And He is with you wherever you are. – Quran 57:4",
  "You must do the things you think you cannot do. – Eleanor Roosevelt",
  "A champion is defined not by their wins but by how they can recover when they fall. – Serena Williams",
  "Be yourself; everyone else is already taken. – Oscar Wilde",
  "Do not wait for leaders; do it alone, person to person. – Mother Teresa",
  "Believe in yourself and all that you are. – Christian D. Larson",
  "Life is short, and it is up to you to make it sweet. – Sarah Louise Delany",
  "With the new day comes new strength and new thoughts. – Eleanor Roosevelt",
  "You don’t have to be perfect to be amazing. – Unknown",
  "And your Lord has decreed that you not worship except Him, and to parents, good treatment. – Quran 17:23",
  "And He found you poor and made [you] self-sufficient. – Quran 93:8",
  "Life is what happens when you’re busy making other plans. – John Lennon",
  "You have within you right now, everything you need to deal with whatever the world can throw at you. – Brian Tracy",
  "What lies behind us and what lies before us are tiny matters compared to what lies within us. – Ralph Waldo Emerson",
  "Your time is limited, don’t waste it living someone else’s life. – Steve Jobs",
  "You must be the change you wish to see in the world. – Mahatma Gandhi",
  "The only way to do great work is to love what you do. – Steve Jobs",
  "Success is how high you bounce when you hit bottom. – George S. Patton",
  "It is never too late to be what you might have been. – George Eliot",
  "The mind is everything. What you think you become. – Buddha",
  "And the disbelievers say, 'Why has a miracle not been sent down to him from his Lord?' Say, 'Indeed, Allah leaves astray whom He wills and guides to Himself whoever turns back.' – Quran 13:27",
  "And do not despair of the mercy of Allah. – Quran 39:53",
  // Add more quotes as needed...
];

const inspirationalQuotes = [
  "Indeed, with hardship [will be] ease. – Quran 94:6",
  "And He is with you wherever you are. – Quran 57:4",
  "So verily, with the hardship, there is relief. – Quran 94:5",
  "Do not lose hope, nor be sad. – Quran 3:139",
  "Indeed, Allah is the best of planners. – Quran 8:30",
  "And whoever fears Allah – He will make for him a way out. – Quran 65:2",
  "And your Lord says, 'Call upon Me; I will respond to you.' – Quran 40:60",
  "Indeed, Allah does not burden a soul beyond that it can bear. – Quran 2:286",
  "And We have certainly made the Quran easy to remember. – Quran 54:17",
  "Indeed, the righteous will be in pleasure. – Quran 83:22",
  "The only way to do great work is to love what you do. – Steve Jobs",
  "Believe you can and you’re halfway there. – Theodore Roosevelt",
  "Your time is limited, don’t waste it living someone else’s life. – Steve Jobs",
  "What lies behind us and what lies before us are tiny matters compared to what lies within us. – Ralph Waldo Emerson",
  "Success is not final, failure is not fatal: It is the courage to continue that counts. – Winston Churchill",
  "You are never too old to set another goal or to dream a new dream. – C.S. Lewis",
  "The future belongs to those who believe in the beauty of their dreams. – Eleanor Roosevelt",
  "Keep your face always toward the sunshine—and shadows will fall behind you. – Walt Whitman",
  "Act as if what you do makes a difference. It does. – William James",
  "The best way to predict the future is to create it. – Peter Drucker",
  "And We have not sent you, [O Muhammad], except as a mercy to the worlds. – Quran 21:107",
  "And if you ask them, 'Who created the heavens and the earth?' They would surely say, 'Allah.' – Quran 31:25",
  "And if you are grateful, I will surely increase your favor. – Quran 14:7",
  "Indeed, Allah is with the patient. – Quran 2:153",
  "Indeed, the promise of Allah is truth. – Quran 10:55",
  "And do not lose hope in the mercy of Allah. – Quran 39:53",
  "And We will surely give them a taste of the lesser punishment. – Quran 32:21",
  "And do not despair of the mercy of Allah. – Quran 39:53",
  "Indeed, those who have believed and done righteous deeds will be in gardens. – Quran 18:107",
  "Indeed, your allies are none but Allah and His Messenger and those who have believed. – Quran 5:55",
  "The pain you feel today is the strength you feel tomorrow. – Unknown",
  "You can’t go back and change the beginning, but you can start where you are and change the ending. – C.S. Lewis",
  "What we think, we become. – Buddha",
  "The only impossible journey is the one you never begin. – Tony Robbins",
  "Your present circumstances don’t determine where you can go; they merely determine where you start. – Nido Qubein",
  "Life isn’t about finding yourself. Life is about creating yourself. – George Bernard Shaw",
  "Everything you’ve ever wanted is on the other side of fear. – George Addair",
  "Success usually comes to those who are too busy to be looking for it. – Henry David Thoreau",
  "Happiness is not something ready made. It comes from your own actions. – Dalai Lama",
  "Life is either a daring adventure or nothing at all. – Helen Keller",
  "Indeed, Allah does not change the condition of a people until they change what is in themselves. – Quran 13:11",
  "And He found you lost and guided [you]. – Quran 93:7",
  "Say, 'O My servants who have believed, fear your Lord.' – Quran 39:10",
  "Indeed, the Most Honorable of you in the sight of Allah is the most righteous of you. – Quran 49:13",
  "And your Lord will give you, and you will be satisfied. – Quran 93:5",
  "And We have created man and We know what his soul whispers to him. – Quran 50:16",
  "And We will certainly give them a taste of the lesser punishment. – Quran 32:21",
  "So be patient. Indeed, the promise of Allah is truth. – Quran 30:60",
  "Indeed, Allah is the Most Forgiving, the Most Merciful. – Quran 39:53",
  "And whoever relies upon Allah, He is sufficient for him. – Quran 65:3",
  "Dream big and dare to fail. – Norman Vaughan",
  "You are stronger than you think. – Unknown",
  "What we think, we become. – Buddha",
  "The struggle you’re in today is developing the strength you need for tomorrow. – Robert Tew",
  "If you want to live a happy life, tie it to a goal, not to people or things. – Albert Einstein",
  "It’s not whether you get knocked down, it’s whether you get up. – Vince Lombardi",
  "Sometimes you will never know the value of a moment until it becomes a memory. – Dr. Seuss",
  "You have within you right now, everything you need to deal with whatever the world can throw at you. – Brian Tracy",
  "The only limit to our realization of tomorrow will be our doubts of today. – Franklin D. Roosevelt",
  "Keep going. Each step may get harder, but don’t stop. The view is beautiful at the top. – Unknown",
  "And We have created you in pairs. – Quran 78:8",
  "And We will surely test you with something of fear and hunger. – Quran 2:155",
  "Indeed, Allah is with the patient. – Quran 2:153",
  "Indeed, the righteous will be in pleasure. – Quran 83:22",
  "And We have sent you, [O Muhammad], as a mercy to the worlds. – Quran 21:107",
  "And your Lord has not taken leave of you, nor has He become displeased. – Quran 93:3",
  "And whoever does an atom's weight of good will see it. – Quran 99:7",
  "Indeed, the promise of Allah is truth. – Quran 10:55",
  "Indeed, with hardship comes ease. – Quran 94:6",
  "In the middle of every difficulty lies opportunity. – Albert Einstein",
  "Success is walking from failure to failure with no loss of enthusiasm. – Winston Churchill",
  "The only way out is through. – Robert Frost",
  "The best way to predict the future is to create it. – Peter Drucker",
  "You are never given a wish without also being given the power to make it come true. – Richard Bach",
  "Your life does not get better by chance, it gets better by change. – Jim Rohn",
  "Life is what happens when you’re busy making other plans. – John Lennon",
  "The pain you feel today is the strength you feel tomorrow. – Unknown",
  "You don’t have to be great to start, but you have to start to be great. – Zig Ziglar",
  "Keep your eyes on the stars, and your feet on the ground. – Theodore Roosevelt",
  "And whoever does a good deed, We will increase for him good therein. – Quran 42:23",
  "And He created you and made for you hearing and vision and hearts; little are you grateful. – Quran 67:23",
  "Indeed, Allah will not change the condition of a people until they change what is in themselves. – Quran 13:11",
  "And We have made the night and the day as two signs. – Quran 17:12",
  "And your Lord will give you, and you will be satisfied. – Quran 93:5",
  "Indeed, those who have believed and done righteous deeds will be in gardens. – Quran 18:107",
  "And if you are grateful, I will surely increase your favor. – Quran 14:7",
  "And your Lord says, 'Call upon Me; I will respond to you.' – Quran 40:60",
  "Indeed, the most honored of you in the sight of Allah is the most righteous of you. – Quran 49:13",
  "And do not kill yourselves [or one another]. – Quran 4:29",
  "The best revenge is massive success. – Frank Sinatra",
  "Opportunities don't happen. You create them. – Chris Grosser",
  "The biggest risk is not taking any risk. – Mark Zuckerberg",
  "Dream it. Wish it. Do it. – Unknown",
  "If you can dream it, you can achieve it. – Zig Ziglar",
  "The secret of getting ahead is getting started. – Mark Twain",
  "The harder you work for something, the greater you’ll feel when you achieve it. – Unknown",
  "Don’t watch the clock; do what it does. Keep going. – Sam Levenson",
  "The only limit to our realization of tomorrow will be our doubts of today. – Franklin D. Roosevelt",
  "Success usually comes to those who are too busy to be looking for it. – Henry David Thoreau",
  "And do not grieve; indeed Allah is with us. – Quran 9:40",
  "And whoever fears Allah, He will make for him a way out. – Quran 65:2",
  "And We have created you in pairs. – Quran 78:8",
  "And do not despair of the mercy of Allah. – Quran 39:53",
  "Indeed, Allah does not change the condition of a people until they change what is in themselves. – Quran 13:11",
  "And your Lord says, 'Call upon Me; I will respond to you.' – Quran 40:60",
  "And We will certainly test you with something of fear and hunger. – Quran 2:155",
  "And if you ask them, 'Who created the heavens and the earth?' They would surely say, 'Allah.' – Quran 31:25",
  "Indeed, the most honored of you in the sight of Allah is the most righteous of you. – Quran 49:13",
  "And do not lose hope in the mercy of Allah. – Quran 39:53",
  "In the end, we only regret the chances we didn't take. – Lewis Carroll",
  "Dream big and dare to fail. – Norman Vaughan",
  "Sometimes you will never know the value of a moment until it becomes a memory. – Dr. Seuss",
  "Everything you’ve ever wanted is on the other side of fear. – George Addair",
  "Success is the sum of small efforts, repeated day in and day out. – Robert Collier",
  "It does not matter how slowly you go as long as you do not stop. – Confucius",
  "If you want something you never had, you have to do something you’ve never done. – Thomas Jefferson",
  "What defines us is how well we rise after falling. – Lionel A. Barrymore",
  "We may encounter many defeats but we must not be defeated. – Maya Angelou",
  "Believe you can and you’re halfway there. – Theodore Roosevelt",
  "Indeed, Allah is with those who are patient. – Quran 2:153",
  "And your Lord is the Forgiving, the Merciful. – Quran 39:53",
  "And He found you lost and guided [you]. – Quran 93:7",
  "Indeed, the righteous will be in pleasure. – Quran 83:22",
  "And whoever does an atom's weight of good will see it. – Quran 99:7",
  "And do not grieve; indeed Allah is with us. – Quran 9:40",
  "And We will surely give them a taste of the lesser punishment. – Quran 32:21",
  "Indeed, with hardship comes ease. – Quran 94:6",
  "Your Lord has not taken leave of you, nor has He become displeased. – Quran 93:3",
  "And whoever relies upon Allah, He is sufficient for him. – Quran 65:3",
  "You are never too old to set another goal or to dream a new dream. – C.S. Lewis",
  "Success usually comes to those who are too busy to be looking for it. – Henry David Thoreau",
  "The best time to plant a tree was twenty years ago. The second best time is now. – Chinese Proverb",
  "With the new day comes new strength and new thoughts. – Eleanor Roosevelt",
  "The purpose of our lives is to be happy. – Dalai Lama",
  "It’s not whether you get knocked down; it’s whether you get up. – Vince Lombardi",
  "Success is not how high you have climbed, but how you make a positive difference to the world. – Roy T. Bennett",
  "What we fear doing most is usually what we most need to do. – Tim Ferriss",
  "The harder you work for something, the greater you’ll feel when you achieve it. – Unknown",
  "Keep your eyes on the stars, and your feet on the ground. – Theodore Roosevelt",
  "And We have created man and We know what his soul whispers to him. – Quran 50:16",
  "Indeed, the most honored of you in the sight of Allah is the most righteous of you. – Quran 49:13",
  "And whoever fears Allah, He will make for him a way out. – Quran 65:2",
  "Indeed, the righteous will be in pleasure. – Quran 83:22",
  "And do not kill yourselves [or one another]. – Quran 4:29",
  "And We have not sent you, [O Muhammad], except as a mercy to the worlds. – Quran 21:107",
  "And your Lord says, 'Call upon Me; I will respond to you.' – Quran 40:60",
  "And if you are grateful, I will surely increase your favor. – Quran 14:7",
  "Indeed, Allah is the Most Forgiving, the Most Merciful. – Quran 39:53",
  "And whoever relies upon Allah, He is sufficient for him. – Quran 65:3"
];


const friendship = [
  "A friend is someone who knows all about you and still loves you. – Elbert Hubbard",
  "Friendship is born at that moment when one person says to another, 'What! You too? I thought I was the only one.' – C.S. Lewis",
  "True friendship comes when the silence between two people is comfortable. – David Tyson",
  "A real friend is one who walks in when the rest of the world walks out. – Walter Winchell",
  "Friendship is the only cement that will ever hold the world together. – Woodrow Wilson",
  "A friend is what the heart needs all the time. – Henry Van Dyke",
  "Friends are the siblings we choose for ourselves. – Judith Seth",
  "The language of friendship is not words but meanings. – Henry David Thoreau",
  "Friendship is always a sweet responsibility, never an opportunity. – Kahlil Gibran",
  "A friend is someone who gives you total freedom to be yourself. – Jim Morrison",
  "Friendship is like a tree. It takes a long time to grow, but once it’s grown, it’s there for life. – Unknown",
  "The greatest gift of life is friendship, and I have received it. – Hubert H. Humphrey",
  "A true friend is someone who is there for you when they would rather be anywhere else. – Len Wein",
  "Friendship improves happiness and abates misery, by the doubling of our joy and the dividing of our grief. – Marcus Tullius Cicero",
  "A friend knows the song in my heart and sings it to me when I have forgotten the words. – Donna Roberts",
  "Friends show their love in times of trouble, not in happiness. – Euripides",
  "The best mirror is an old friend. – George Herbert",
  "Friendship is a single soul dwelling in two bodies. – Aristotle",
  "There are no strangers here; Only friends you haven’t yet met. – William Butler Yeats",
  "A true friend is the greatest of all blessings. – Buddha",
  "A good friend is like a four-leaf clover; hard to find and lucky to have. – Irish Proverb",
  "Friendship is the golden thread that ties the heart of all the world. – John Evelyn",
  "In the cookie of life, sisters are the chocolate chips. – Unknown",
  "Friends are those rare people who ask how we are and then wait to hear the answer. – Ed Cunningham",
  "Friendship is not about whom you have known the longest; it’s about who came and never left your side. – Unknown",
  "A true friend is someone who accepts your past, supports your present, and encourages your future. – Unknown",
  "Friendship is the comfort of knowing that even when you feel alone, you aren’t. – Unknown",
  "Good friends are like stars. You don’t always see them, but you know they’re always there. – Unknown",
  "A friend is someone who can see the truth and pain in you even when you are fooling everyone else. – Unknown",
  "A true friend is one who overlooks your failures and tolerates your success. – Doug Larson",
  "Friends are the family we choose. – Unknown",
  "Friendship is the source of the greatest pleasures, and without friends even the most agreeable pursuits become tedious. – Thomas Aquinas",
  "A friend is someone who makes it easy to believe in yourself. – Heidi Wills",
  "Friendship is a word, the very sight of which in print makes the heart warm. – Augustine Birrell",
  "The most beautiful discovery true friends make is that they can grow separately without growing apart. – Elisabeth Foley",
  "A good friend will always stab you in the front. – Oscar Wilde",
  "Friendship is the greatest gift of life. – Unknown",
  "A friend is someone who understands your past, believes in your future, and accepts you just the way you are. – Unknown",
  "A true friend is someone who listens to your story without judgment. – Unknown",
  "Friendship is the wine of life. – Edward Young",
  "A friend is one who knows you and loves you just the same. – Elbert Hubbard",
  "True friendship is like sound health; the value of it is seldom known until it is lost. – Charles Caleb Colton",
  "Good friends are like stars; you don’t always see them, but you know they are always there. – Unknown",
  "The most I can do for my friend is simply be his friend. – Henry David Thoreau",
  "Friendship is the only ship that never sinks. – Unknown",
  "A true friend is the greatest of all blessings. – Buddha",
  "A friend is someone who understands your past, believes in your future, and accepts you just the way you are. – Unknown",
  "Friendship is a tree. It takes a long time to grow, but once it’s grown, it’s there for life. – Unknown",
  "The best time to make friends is before you need them. – Ethel Barrymore",
  "Friendship is a sheltering tree. – Samuel Taylor Coleridge",
  "There are friends, there is family, and then there are friends that become family. – Unknown",
  "Friendship is the comfort of knowing that even when you feel alone, you aren’t. – Unknown",
  "A friend is someone who gives you total freedom to be yourself. – Jim Morrison",
  "A true friend is someone who sees the pain in your eyes while everyone else believes the smile on your face. – Unknown",
  "The best way to predict the future is to create it with your friends. – Unknown",
  "In the end, we will remember not the words of our enemies, but the silence of our friends. – Martin Luther King Jr.",
  "Friendship is like a flower; it needs care and attention to bloom. – Unknown",
  "A friend is one who believes in you when you have ceased to believe in yourself. – Unknown",
  "The greatest gift is not found in a store but in the hearts of true friends. – Unknown",
  "A friend is a treasure. – Unknown",
  "Friendship is not a big thing, it’s a million little things. – Unknown",
  "A friend is someone who knows all about you and still loves you. – Elbert Hubbard",
  "True friendship is a plant of slow growth. – George Washington",
  "Friendship is the only ship that never sinks. – Unknown",
  "A friend is what the heart needs all the time. – Henry Van Dyke",
  "Friendship is the golden thread that ties the heart of all the world. – John Evelyn",
  "True friends are never apart, maybe in distance but never in heart. – Helen Keller",
  "A friend is someone who makes you laugh even when you feel like crying. – Unknown",
  "A friend is a person with whom I may be sincere. – Ralph Waldo Emerson",
  "True friendship is a rare treasure. – Unknown",
  "A friend is someone who makes it easy to believe in yourself. – Heidi Wills",
  "Friendship is the source of the greatest pleasures, and without friends even the most agreeable pursuits become tedious. – Thomas Aquinas",
  "A good friend can tell you what you don’t want to hear, but need to hear. – Unknown",
  "Friendship is not about whom you have known the longest; it’s about who came and never left your side. – Unknown",
  "A true friend is someone who overlooks your failures and tolerates your success. – Doug Larson",
  "Friendship is a sheltering tree. – Samuel Taylor Coleridge",
  "A friend is someone who can see the truth and pain in you even when you are fooling everyone else. – Unknown",
  "The most beautiful discovery true friends make is that they can grow separately without growing apart. – Elisabeth Foley",
  "A friend is someone who gives you total freedom to be yourself. – Jim Morrison",
  "True friends are never apart, maybe in distance but never in heart. – Helen Keller",
  "Friendship is the wine of life. – Edward Young",
  "A true friend is one who overlooks your failures and tolerates your success. – Doug Larson",
  "A friend is someone who knows you and loves you just the same. – Elbert Hubbard",
  "A friend is what the heart needs all the time. – Henry Van Dyke",
  "The best mirror is an old friend. – George Herbert",
  "Friendship is the only cement that will ever hold the world together. – Woodrow Wilson",
  "The greatest gift of life is friendship, and I have received it. – Hubert H. Humphrey",
  "A good friend is like a four-leaf clover; hard to find and lucky to have. – Irish Proverb",
  "Friendship is like a tree. It takes a long time to grow, but once it’s grown, it’s there for life. – Unknown",
  "A real friend is one who walks in when the rest of the world walks out. – Walter Winchell",
  "A true friend is the greatest of all blessings. – Buddha",
  "Friends are the siblings we choose for ourselves. – Judith Seth",
  "In the cookie of life, sisters are the chocolate chips. – Unknown",
  "A friend is someone who knows all about you and still loves you. – Elbert Hubbard",
  "Friendship is born at that moment when one person says to another, 'What! You too? I thought I was the only one.' – C.S. Lewis"
];


const family = [
  "And We have enjoined upon man [care] for his parents. – Quran 29:8",
  "Your Lord has decreed that you not worship except Him, and to parents, good treatment. – Quran 17:23",
  "And We have enjoined upon man [care] for his parents. But if they endeavor to make you associate with Me that of which you have no knowledge, do not obey them. To Me is your return, and I will inform you about what you used to do. – Quran 29:8",
  "And do good to parents, relatives, orphans, the needy, the near neighbor, the neighbor farther away, the companion at your side, the companion along the journey, and those whom your right hands possess. – Quran 4:36",
  "He has made for you from your homes a place of rest and made for you from the hides of the animals tents which you find light on the day of travel and when you stop for rest. – Quran 16:80",
  "Your wealth and your children are but a trial, and Allah has. – Quran 64:15",
  "And do not kill your children for fear of poverty. We provide for them and for you. – Quran 17:31",
  "And We have certainly created man and We know what his soul whispers to him, and We are closer to him than [his] jugular vein. – Quran 50:16",
  "And We have enjoined upon man [care] for his parents. – Quran 31:14",
  "Wealth and children are [but] adornment of the worldly life. But the enduring good deeds are better to your Lord for reward and better for [one's] hope. – Quran 18:46",
  "And We have enjoined upon man, his parents, good treatment. – Quran 46:15",
  "And We have made the child of man, for a purpose, as a trial for him. – Quran 67:2",
  "Indeed, Allah commands you to render trusts to whom they are due and when you judge between people to judge with justice. – Quran 4:58",
  "And We have sent Our messengers with clear signs and sent down with them the Scripture and weight that the people may maintain [therein] justice. – Quran 57:25",
  "The example of those who spend their wealth in the way of Allah is like a seed of grain that sprouts into seven ears; in every ear is a hundred grains. – Quran 2:261",
  "And do not turn your cheek [in contempt] toward people and do not walk through the earth exultantly. – Quran 31:18",
  "And speak to people good [words]. – Quran 2:83",
  "Indeed, those who believed and done righteous deeds will have the Gardens of Paradise as a lodging. – Quran 18:107",
  "And do not covet that by which Allah has made some of you exceed others. – Quran 4:32",
  "And whoever among you does good deeds and is a believer, his effort will not be rejected, and We will record it for him. – Quran 21:94",
  "And do good, for indeed, Allah loves the doers of good. – Quran 2:195",
  "And We have certainly created man and We know what his soul whispers to him, and We are closer to him than his jugular vein. – Quran 50:16",
  "Indeed, Allah commands you to render trusts to whom they are due and when you judge between people to judge with justice. – Quran 4:58",
  "And those who say, 'Our Lord, grant us from among our wives and offspring comfort to our eyes and make us an example for the righteous.' – Quran 25:74",
  "And We have enjoined upon man [care] for his parents. – Quran 31:14",
  "And We have made the child of man a trial for him. – Quran 67:2",
  "And We have enjoined upon man [care] for his parents. – Quran 46:15",
  "A father’s love is reflected in his children. – Unknown",
  "A mother is she who can take the place of all others but whose place no one else can take. – Unknown",
  "Siblings are the greatest gift of life. – Unknown",
  "A true friend is someone who is always there for you, no matter what. – Unknown",
  "Family is not an important thing. It’s everything. – Michael J. Fox",
  "A friend is someone who knows all about you and still loves you. – Elbert Hubbard",
  "A sister is both your mirror and your opposite. – Elizabeth Fishel",
  "A brother is a friend given by nature. – Jean Baptiste Leguve",
  "Family is where life begins and love never ends. – Unknown",
  "Friends are the family we choose for ourselves. – Unknown",
  "A mother’s arms are made of tenderness, and children sleep soundly in them. – Victor Hugo",
  "A father is someone you look up to no matter how tall you grow. – Unknown",
  "Siblings may fight, but they will always be there for each other. – Unknown",
  "A good friend is like a four-leaf clover; hard to find and lucky to have. – Irish Proverb",
  "Family is the compass that guides us; they are the inspiration to reach great heights. – Brad Henry",
  "A mother understands what a child does not say. – Jewish Proverb",
  "There is no buddy like a brother. – Unknown",
  "A friend is one who knows you and loves you just the same. – Elbert Hubbard",
  "Friendship is born at that moment when one person says to another, 'What! You too? I thought I was the only one.' – C.S. Lewis",
  "The love of a family is life’s greatest blessing. – Unknown",
  "True friendship is a plant of slow growth. – George Washington",
  "Siblings: your only enemy you can’t live without. – Unknown",
  "In family life, love is the oil that eases friction, the cement that binds closer together, and the music that brings harmony. – Friedrich Nietzsche",
  "A friend is someone who gives you total freedom to be yourself. – Jim Morrison",
  "Family is the anchor that holds us through life’s storms. – Unknown",
  "There is no friend like a sister in calm and stormy weather. – Christina Rossetti",
  "A father is a man who expects his children to be as good as he meant to be. – Carol Coats",
  "Friends are the siblings we choose for ourselves. – Unknown",
  "A brother shares childhood memories and grown-up dreams. – Unknown",
  "A mother’s love is more beautiful than any fresh flower. – Debasish Mridha",
  "The bond that links your true family is not one of blood, but of respect and joy in each other’s life. – Richard Bach",
  "A good friend is like a four-leaf clover; hard to find and lucky to have. – Irish Proverb",
  "The love of a family is life’s greatest blessing. – Unknown",
  "Sisters are different flowers from the same garden. – Unknown",
  "Friends are the family we choose for ourselves. – Unknown",
  "In family life, love is the oil that eases friction, the cement that binds closer together, and the music that brings harmony. – Friedrich Nietzsche",
  "A sister is both your mirror and your opposite. – Elizabeth Fishel",
  "Brothers aren’t just family; they are best friends for life. – Unknown",
  "The family is one of nature's masterpieces. – George Santayana",
  "A father’s love is forever imprinted on his child’s heart. – Unknown",
  "Family is where life begins and love never ends. – Unknown",
  "A friend is one who knows you and loves you just the same. – Elbert Hubbard",
  "A mother’s love is more beautiful than any fresh flower. – Debasish Mridha",
  "Siblings are the greatest gift of life. – Unknown",
  "A true friend is someone who sees the pain in your eyes while everyone else believes the smile on your face. – Unknown",
  "The love of a family is life’s greatest blessing. – Unknown",
  "Family is not an important thing. It’s everything. – Michael J. Fox",
  "There is no buddy like a brother. – Unknown",
  "A friend is someone who gives you total freedom to be yourself. – Jim Morrison",
  "In family life, love is the oil that eases friction, the cement that binds closer together, and the music that brings harmony. – Friedrich Nietzsche",
  "A brother shares childhood memories and grown-up dreams. – Unknown",
  "A father is a man who expects his children to be as good as he meant to be. – Carol Coats",
  "Family is the anchor that holds us through life’s storms. – Unknown",
  "There is no friend like a sister in calm and stormy weather. – Christina Rossetti",
  "A good friend is like a four-leaf clover; hard to find and lucky to have. – Irish Proverb",
  "Sisters are different flowers from the same garden. – Unknown",
  "A mother understands what a child does not say. – Jewish Proverb",
  "True friendship is a plant of slow growth. – George Washington",
  "A sister is both your mirror and your opposite. – Elizabeth Fishel",
  "Brothers aren’t just family; they are best friends for life. – Unknown",
  "The family is one of nature's masterpieces. – George Santayana",
  "A father’s love is forever imprinted on his child’s heart. – Unknown",
  "Family is where life begins and love never ends. – Unknown",
  "A friend is one who knows you and loves you just the same. – Elbert Hubbard",
  "A mother’s love is more beautiful than any fresh flower. – Debasish Mridha",
  "Siblings are the greatest gift of life. – Unknown",
  "A true friend is someone who sees the pain in your eyes while everyone else believes the smile on your face. – Unknown",
  "Family is not an important thing. It’s everything. – Michael J. Fox"
];


// Add event listeners to the buttons
document.querySelectorAll('.quote-btn').forEach(button => {
  button.addEventListener('click', () => {
      const category = button.getAttribute('data-category');
      getQuote(category);
  });
});

async function getQuote(category) {
  const quoteElement = document.getElementById('quote');
  quoteElement.classList.remove('fade-in');

  setTimeout(() => {
      let message;

      if (category === 'bad-day') {
          // Select a random quote from the badDayQuotes array
          const randomIndex = Math.floor(Math.random() * badDayQuotes.length);
          message = badDayQuotes[randomIndex];
      } else if (category === 'inspirational') {
        // Select a random quote from the inspirationalQuotes array
        const randomIndex = Math.floor(Math.random() * inspirationalQuotes.length);
        message = inspirationalQuotes[randomIndex];
      } else if (category === 'friendship') {
        const randomIndex = Math.floor(Math.random() * friendship.length);
        message = friendship[randomIndex];
      } else if (category === 'family') {
        const randomIndex = Math.floor(Math.random() * family.length);
        message = family[randomIndex];
      } else if (category === 'random') {
        // Combine all quotes into one array
        const allQuotes = [
            ...badDayQuotes,
            ...inspirationalQuotes,
            ...friendship,
            ...family
        ];
        // Select a random quote from the combined array
        const randomIndex = Math.floor(Math.random() * allQuotes.length);
        message = allQuotes[randomIndex];
      } else {
          message = "Latest BTC Price: $60787.17"; // Default message
      }

      // Display the selected message in the quote element
      quoteElement.innerText = message;
      quoteElement.classList.add('fade-in');
  }, 100);
}
